### ISSUE TITLE
Updating dates often doesn't take

### ISSUE THREAD

**Issue by marcesher** [etsy/morgue#53]
In an existing postmortem, I'm trying to update the dates (start, end, detect). More often than not, the update doesn't "take", and refreshing the screen shows the old values. If I keep trying -- I've seen it happen after just trying one more time, and trying maybe 8 more times -- it'll eventually work. But there's no pattern to it.

I see no errors in the Chrome console or the apache error_log file

**Comment by cyberrodent** [comment]
Hi @marcesher. Are you seeing the green highlight appear at all?  The UI can be a bit non-obvious in that the save is triggered by clicking outside of the form element (onBlur).

The updates would be sending an http PUT back to your server.  Can you check if you are seeing those in your access log?

**Comment by marcesher** [comment]
@cyberrodent Definitely seeing the green "Success" message. I'll check the logs when I'm back to work tomorrow

**Comment by marcesher** [comment]
@cyberrodent Here's what I'm seeing:

1) if I use the datepicker, a PUT request is sent, returns 201. I see this in both Chrome dev tools and the apache log. I get the green "Date has been updated" message. If I refresh the page, I see the update did not take
2) If I manually set the date, I see the same thing in dev tools and the apache log, I see the updated message, and if I refresh the screen, I see that the field updated successfully.

So: same traffic in logs, and nothing at all indicating a difference between using the datepicker vs manually changing the date.

**Comment by cyberrodent** [comment]
working at the lastes revision I can now reproduce this.  This bug is there even after adding in the missing script "/assets/js/jquery.plugin.min.js"

**Comment by marcesher** [comment]
@cyberrodent Thanks for following up. So to be clear, the delete issue is/was related to the missing plugin javascript, but the save error is not... correct?

**Comment by cyberrodent** [comment]
as of a21b943d72bc3548b94672a1268978be38a27097 this should be resolved
