### ISSUE TITLE
Latest morgue will not run; issues PHP error

### ISSUE THREAD

**Issue by marcesher** [etsy/morgue#90]
Pulling the latest morgue code, I get this when running within apache:

PHP Parse error:  syntax error, unexpected '[' in /var/www/morgue/htdocs/index.php on line 301

This is with PHP 5.3.3 and Apache 2.2.15

**Comment by mmercedes** [comment]
Hi Marc,

Unfortunately, I'm not seeing this error. I currently have Apache 2.4.6 and PHP 5.5.17 though which might explain why.

**Comment by rlerdorf** [comment]
@mmercedes @marcesher The short array syntax [...] vs. array(...) was introduced in PHP 5.4. @marcesher is running a 5-year old PHP 5.3.3 which was EOL'ed in 2014.

**Comment by marcesher** [comment]
Upgrading to 5.5 did it. I'll submit a PR for the README change to indicate 5.4 is required. Thanks all.
